target_source = "host_list"
install_list = [[C:\pi\config\install_list.lua]]
installed_list = [[C:\pi\config\installed.lua]]
package_list = [[C:\pi\config\packages.lua]]
connection_list = [[C:\pi\config\connections.lua]]
log_list = [[C:\pi\config\log.lua]]
profile_list = [[C:\pi\config\profiles.lua]]
host_list = [[C:\pi\config\hosts.lua]]
status_gui = [[C:\pi\pi_status_gui.exe /close_when_done]]
run = "start"
display_target = "winlogon"